dist/index-cli.js, dist/index.js, src/app/compiler/dependencies.ts, test/src/cli.spec.ts, test/src/sample-files/bar.component.ts
Made the last one against the wrong branch 😃
=> fix: exclude internal members from generated documentation

README.md
I'm guessing it is exclude and not export
=> Use the proper property name

index.html
according to documentation - https://compodoc.github.io/website/guides/installation.html
=> fixed npm command

src/app/compiler/dependencies.ts, src/templates/partials/pipe.hbs
https://github.com/compodoc/compodoc/issues/188
=> [FEATURE] Add an interactive examples tab: add Examples tab to Pipe

package.json, rollup/rollup.config.js, src/app/compiler/codegen.ts, src/app/compiler/dependencies.interfaces.ts, src/app/compiler/dependencies.ts, src/app/compiler/deps/component-dep.factory.ts, src/app/compiler/deps/directive-dep.factory.ts, src/app/compiler/deps/helpers/class-helper.ts, src/app/compiler/deps/helpers/component-helper.ts, src/app/compiler/deps/helpers/js-doc-helper.ts, src/app/compiler/deps/helpers/module-helper.ts, src/app/compiler/deps/helpers/symbol-helper.ts, src/app/compiler/deps/module-dep.factory.ts, src/app/compiler/node-object.interface.ts, src/app/engines/components-tree.engine.ts, src/utils/utils.ts, test/src/cli/cli-generation-big-app.spec.ts, test/src/helpers.ts, tsconfig.json, tslint.json
This ended up a little larger than i would have wanted, but i fell like the change improved the read-ability a bit while adhering to the tslint rules (some of which have changed to reflect code).
Also, i have parted out a part of dependencies.ts to smaller classes and started adding more types (Which i will continue when this have been merged, but the PR seemed rather large already)
When running 'npm run test', some of the tests results in '"before all" hook' error, and Im not sure if it just on my computer, so if you could run test before and maybe help point out the error since i could not locate it, if there is one :)
=> Tslint - part 1

src/resources/styles/compodoc.css
Just add text ellipsis.
Thank you 👍
=> feat(desgin): ellipsis list item text

src/app/engines/export.engine.ts
Right now the output is very ugly, as its not properly formatted. This will format the JSON stringified output :)
=> feat(export.engine): beautify formats JSON output

CONTRIBUTING.md
Remove duplicate paragraph from CONTRIBUTING.md
=> doc: remove duplicate content from CONTRIBUTING.md

src/app/compiler/dependencies.interfaces.ts, src/app/compiler/dependencies.ts, src/resources/styles/compodoc.css, src/templates/partials/injectable.hbs
1) Added examples tab to services
2) Added hiding of example-url tag on Info tab
=> 1) Added examples tab to services and hiding of example-url tag on Info tab

src/resources/styles/compodoc.css
=> Fixing ordered lists in README.md files

src/resources/styles/compodoc.css, src/templates/partials/modules.hbs
Fixing issue with gaps being left in modules page
=> [BUG] Fixing Module card leaving gaps in rows

src/index-cli.ts
This code is duplicate
https://github.com/alan-agius4/compodoc/blob/eb25e1a5fe4650e69f3b2e90c66a1280ee217ccf/src/index-cli.ts#L97
https://github.com/alan-agius4/compodoc/blob/eb25e1a5fe4650e69f3b2e90c66a1280ee217ccf/src/index-cli.ts#L101
=> refactor(cli): remove duplicate code

src/templates/partials/menu.hbs
Fixing the widths so the menu text is aligned
=> Fixing icon widths

src/app/engines/markdown.engine.ts, src/resources/styles/compodoc.css, src/templates/partials/component.hbs, src/templates/partials/coverage-report.hbs
=> fix(UI): ensure examples tab has only one scrollbar

src/app/application.ts, src/app/configuration.ts, src/app/interfaces/main-data.interface.ts, src/index-cli.ts, src/templates/partials/component.hbs, src/utils/constants.ts, src/utils/defaults.ts, test/src/bar.component.ts, test/src/cli/cli-generation.spec.ts, test/src/cli/cli-options.spec.ts, test/src/sample-files/bar.component.ts, test/src/sample-files/bar.style.scss, test/src/sample-files/bar2.style.scss
Hi,
here is my solution for #648
=> Style source tab

package-lock.json, package.json
Fixes a vulnerability issue
https://github.com/tapio/live-server/issues/285
https://github.com/dominictarr/event-stream/issues/116
=> Update live server - Fixes Vulnerability issue

src/app/engines/html-engine-helpers/parse-description.helper.ts
missing 's' at the end of 'miscellaneous'
=> Fixed a small type

src/app/application.ts, src/app/configuration.ts, src/app/interfaces/configuration-file.interface.ts, src/app/interfaces/main-data.interface.ts, src/config/schema.json, src/index-cli.ts, src/templates/page.hbs, src/templates/partials/menu.hbs, src/utils/defaults.ts, test/src/cli/cli-disable-options.spec.ts, test/src/test-templates/page.hbs
=> feat(CLI): disableDependencies flag

src/app/engines/export-json.engine.ts, src/app/interfaces/export-data.interface.ts
The json exporter is not exporting the guards and interceptors from the main data. This pull request simply adds the guards and interceptors to the export data.
=> Fix: Added missing guards and interceptors to the json exporter.

src/utils/router-parser.util.ts
fix suggested in https://github.com/compodoc/compodoc/issues/895
=> Angular lazy loading fix - extra undefined check in router-parser

src/app/compiler/angular-dependencies.ts, src/app/compiler/angular/deps/controller-dep.factory.ts, src/app/compiler/angular/deps/helpers/class-helper.ts, test/src/cli/cli-export.spec.ts, test/src/helpers.ts
=> Add raw descriptions

src/app/compiler/angular/deps/helpers/class-helper.ts, test/fixtures/todomvc-ng2/src/app/shared/components/dumb-component.ts, test/fixtures/todomvc-ng2/src/app/shared/components/dumb-parent-component.ts, test/fixtures/todomvc-ng2/src/app/shared/directives/do-nothing.directive.ts, test/fixtures/todomvc-ng2/src/app/shared/interfaces/interfaces.ts, test/fixtures/todomvc-ng2/src/app/shared/interfaces/time.interface.ts, test/fixtures/todomvc-ng2/src/app/shared/pipes/first-upper.pipe.ts, test/src/cli/cli-export.spec.ts
Closes [#995](https://github.com/compodoc/compodoc/issues/995)
=> provide jsdoctags
