- package.json
It looks like 1.0.0 of this module was accidentally published to npm, meaning the caret in package.json will always install that version rather than the later alpha versions, which don't have the `svg-to-png` dependency which causes a lot of warnings on npm install.
> fix: pin angular2-dependencies-graph version

- src/app/engines/search.engine.ts
**Invalid JSON is creating an issue when rendering the object to the template**
I found cases where modules where being included twice, I believe it's due to the "replace" on the `doc.url`. This formed an invalid json object when inserted into the .hbs template. Now it only writes to the object when the property doesn't exist, this fixes this bug but potentially there is a better way of handling the issue.
Related to #187
> fix(search-engine): COMPODOC_SEARCH_INDEX

- src/app/compiler/dependencies.ts
- src/app/compiler/deps/component-dep.factory.ts
- src/app/compiler/deps/directive-dep.factory.ts
- src/app/compiler/deps/helpers/class-helper.ts
- src/app/compiler/deps/helpers/component-helper.ts
- src/app/compiler/deps/helpers/module-helper.ts
- src/app/compiler/deps/helpers/symbol-helper.spec.ts
- src/app/compiler/deps/helpers/symbol-helper.ts
- src/app/compiler/deps/module-dep.factory.ts
- src/utils/ts-printer.util.ts
* Removed NsModuleCache since i could not find any usages
* Added types to properties, can maybe be more specific (Is ObjectLiteralElementLike like ts typings says, but when debugging only PropertyAssignment was found)
* Added some test to SymbolHelper to ensure changes does not change behavior
> refactor(SymbolHelper)

- test/src/cli/cli-generation.spec.ts
Why:
* Some tests were not passing because of path separator
* Other tests were failling because of process timeout
This change addresses the need by:
* Normalizing the paths in IncludeParser
* Increased timeout (5s to 20s)
> fix(tests): Fixed tests on Windows

- src/app/compiler/deps/helpers/class-helper-spec/class-helper.visitType.spec.ts
- src/app/compiler/deps/helpers/class-helper.ts
- src/utils/kind-to-type.ts
Why:
* Composed types were not rendered correctly sometimes
* Union types were being translated to undefined or empty
This change addresses the need by:
* Refactored visitType
* Included spec for union type
Before the fix:
After the fix:
> fix(class-helper#visitType) Fix union type and composed type

- src/app/application.ts
- test/src/cli/cli-generation.spec.ts
It certanly brokes previous behaviour, but I would expect --assetsFolder to copy only the **last** directory on the passed path.
Current behaviour is a bit buggy when passing relative directories:
```bash
/home/user/project $ ./node_modules/.bin/compodoc -p tsconfig.json --assetsFolder ../project2/assets
```
That command will generate a copy of _/home/user/project2/assets_ on _/home/user/project/project2/assets_ and not on _/home/user/project /documentation/ as it could be expected.
This PR will use path.basename before copying the directory; so previoud command will generate a folder on _/home/user/project/documentation/assets_ with the content fount on _/home/user/project/project2/assets_.
> fix:--assetsFolder uses only last directory name on copy

- src/app/application.ts
- src/app/engines/html-engine-helpers/parse-description.helper.ts
- src/app/engines/html-engine-helpers/relative-url.helper.ts
- src/resources/js/search/search.js
- src/resources/styles/compodoc.css
- src/templates/partials/menu.hbs
- test/src/cli/cli-additional.spec.ts
- test/src/todomvc-ng2/additional-doc/edition/level3.md
- test/src/todomvc-ng2/additional-doc/edition/level4.md
- test/src/todomvc-ng2/additional-doc/edition/level5.md
- test/src/todomvc-ng2/additional-doc/edition/level6.md
- test/src/todomvc-ng2/additional-doc/summary.json
Right now, only 2 levels of depth are supported.
I have had to refactor a little bit the _prepareExternalIncludes_ method, and have decided to limit in *5* levels of depth (which applies across the application, allthought it only affects on the "--includes" folder (I think).
I have added a logger.error whenever someone tries to set more than 5 levels of depth on a summary.json file.
> refactor: prepareExternalIncludes parses children recursively

- src/templates/partials/menu.hbs
This causes problems when hosting as the URL will resolve to ".//images/compodoc-vectorise-inverted.svg". It appears the prepending forward slash is not necessary (as the relativeURL function is suffixed with a "/")
> Removed relative URL helper function from logo img tag

- CONTRIBUTING.md
- Missing double quotes ;
- Use relative path to call on `compodoc` binary, because it wasn't linked before.
> docs(CONTRIBUTING): fix typos in contributing guide

- src/templates/partials/miscellaneous-enumerations.hbs
- src/templates/partials/miscellaneous-functions.hbs
- src/templates/partials/miscellaneous-typealiases.hbs
- src/templates/partials/miscellaneous-variables.hbs
- test/src/cli/cli-generation-big-app.spec.ts
- test/src/todomvc-ng2/src/app/shared/miscellaneous/miscellaneous.ts
Currently there is subtle error in templates that causes @link from miscellaneous to have missing '../' from href paths. Please see https://stomp-js.github.io/api-docs/latest/miscellaneous/functions.html (notice link to `RxStompService`.
This commit is for your review. I will make changes as per your suggestions.
Currently I have added test case for only functions, if you find the approach alright, I will add test cases for enumerations, types, and variables.
> fix(app): href paths for @link in miscellaneous

- src/app/engines/markdown.engine.ts
Hi,
The #750 problem was due to the inclusion of the Markdown engine to PDF in the commit 1d9b49f30b6df9ffc30b43ad4657d53e51ea84e0
In this engine it is established that the Marked instance (shared between this engine and Markdown to render the HTML pages) does not use the Github Flavored Markdown on which the code blocks depend. I have enabled the GFM in the Markdown engine, which makes the code blocks work correctly again. I haven't touched the PDF engine to enable it in this one since I observe that it is currently in development and I don't know what is the expected behavior for this part.
Greetings.
> fix(Engine): Code blocks in Markdown not work as expected

- src/app/application.ts
- src/app/engines/file.engine.ts
Do not asynchronously queue writes of the output files when all the
renders are happening on the same the same tick. On large datasets,
this causes the output to stay in memory until all the renders are done.
In a pathologic case we observed heap usage grow to 22GB (!).
Another different way to fix this would be wrap the `HtmlEngine.render` operation in an async hop (e.g. via a Promise). However, I prefer the solution in this PR as it keeps the lifetime of the rendered data is as small as possible – no need to keep it alive across turns of the even loop.
The pathological example where we observed was in https://github.com/googleapis/google-api-nodejs-client. Reproducing the issues should be as simple as cloning the repo; `npm i` and then `node --max-old-space-size=23000 …
> Avoid pathological out of memory on large datasets

- package-lock.json
- package.json
The package `opencollective` is [officially deprecated](https://github.com/opencollective/opencollective-postinstall/issues/15#issuecomment-459245103). The new replacement `opencollective-postinstall` contains functionality to disable the Open Collective message (e.g. CI) to resolve issues like https://github.com/opencollective/opencollective-postinstall/issues/15.
**Fixes** #803
> compodoc: upgrade to opencollective-postinstall

- CONTRIBUTING.md
- src-refactored/core/entities/public-configuration.ts
- src-refactored/core/entities/public-flags.ts
- src/app/configuration.ts
- src/app/interfaces/main-data.interface.ts
- src/index-cli.ts
- src/resources/js/search/search-lunr.js
- src/resources/js/search/search.js
- src/templates/page.hbs
- src/utils/defaults.ts
- test/fixtures/test-templates/page.hbs
- test/src/cli/cli-max-search-results.spec.ts
Fixing issue #811  for adding a max search results to the options.
This was tested for the options 0, numerous numbers and with the default for the compodoc-demo-todomvc-angular project.
I also included a small fix for the contributing documentation.
> max-search-results-811

- src/utils/router-parser.util.ts
- test/fixtures/todomvc-ng2-simple-routing/src/app/about/about-routing.module.ts
- test/fixtures/todomvc-ng2-simple-routing/src/app/about/about.component.html
- test/fixtures/todomvc-ng2-simple-routing/src/app/about/about.component.ts
- test/fixtures/todomvc-ng2-simple-routing/src/app/about/about.module.ts
- test/fixtures/todomvc-ng2-simple-routing/src/app/about/index.ts
- test/fixtures/todomvc-ng2-simple-routing/src/app/app-routing.module.ts
- test/src/cli/cli-routes-graph.spec.ts
This commit adds support for the new loadChildren lazy loading syntax introduced in Angular 8 by using a regular expression to transform the content to the old syntax prior to building the route tree.
> fix(app): support new lazy loading syntax in Angular 8

- test/src/cli/cli-additional.spec.ts
- test/src/cli/cli-duplicates.spec.ts
- test/src/cli/cli-generation-big-app.spec.ts
- test/src/cli/cli-uniqid.spec.ts
Change tests evaluating HTML output to use EOL constant from OS
module instead of hardcoded \n. Also update uniqid spec to account
for different MD5s on Windows due to the difference path separator.
> test: fix unit tests failing on Windows

- src/utils/router-parser.util.ts
Remove the CWD from the import path before replacing backslashes with
forward slashes. Converting the slashes first causes the CWD replace to
fail on Windows.
> fix(app): fix path separator replace on Windows during route processing

- src-refactored/infrastructure/angular/angular-api.util.ts
Was unsure about how to handle this as nothing is wrong, there isn't a bug so I wouldn't want to clutter issues and it's in the refactored part of the repo which I can't find much talk about what the plans are outside of the todos, which as an outsider I wouldn't have any idea what the progress is/full goal. 
But anyway, I was looking around and noticed this, the function is going through the entire list of AngularApis and all their items, even after one is found. So I modified it to use some which can shortcircuit once the api is found. I also didn't see a reason to use lodash here as it's all just array that the native functions can handle so I removed that file dependency. 
The current angular-api.util also has the same setup, so if this idea is approved I could update that one as well …
> update(angular-util): update findApi to reduce runtime

- src/index-cli.ts
When using the include entries from tsconfig it will now not exclude tsx files anymore
> fix(cli): tsx files not considered in include entries

- src/index-cli.ts
- src/utils/utils.ts
In our project we have .data folder, containing some folders not accessible by current user.
There is no way to exclude it from being scanned by `findit2`.
Current behaviour: documentation generation fails with EACCESS error
New behaviour: successful generation with warning
```
[19:29:23] Ignoring inaccessible folder: /home/denis/projects/jerry/.data/postgresql
```
I planned to add unit test to `utils.ts`, but it seems project have no unit tests yet, only integration and e2e suites, so I decided to not add the whole setup and just rely on current tests to pass.
Sorry for closing and reopening, wasn't intended to.
> fix: generating documentation on project including inacessible folders

- src/app/compiler/angular/deps/helpers/class-helper.ts
- test/fixtures/todomvc-ng2/src/app/about/about.component.html
- test/fixtures/todomvc-ng2/src/app/about/about.component.ts
- test/src/cli/cli-generation-big-app.spec.ts
This commit adds support to extract inferred types on Angular
input attributes. E.g. `@Input() name = ''`
Re-creation of #946
Closes #896
> feat(app): add support for inferred input types

- src/utils/extends-merger.util.ts
Hi, in this pull request I'm trying to solve a problem that I described on #1034 
Today, the inherited class members are straightforward appended to the child class. In the new code, I'm just checking if the class members are also defined in the child class, and if they are, I just copy the `inheritance` metadata object into the child class member.
> fix(app): merge overridden with inherited class members so they are not duplicated in the generated docs

- src/app/compiler/angular-dependencies.ts
- src/app/compiler/angular/dependencies.interfaces.ts
- src/app/compiler/angular/deps/helpers/class-helper.ts
- test/fixtures/todomvc-ng2-duplicates/src/app/shared/interfaces/clock.interface.ts
- test/fixtures/todomvc-ng2-duplicates/src/app/shared/pipes/first-upper.pipe.ts
- test/fixtures/todomvc-ng2-duplicates/src/app/shared/services/todo.store.ts
- test/fixtures/todomvc-ng2-ignore/src/app/shared/interfaces/clock.interface.ts
- test/fixtures/todomvc-ng2-ignore/src/app/shared/pipes/first-upper.pipe.ts
- test/fixtures/todomvc-ng2-ignore/src/app/shared/services/todo.store.ts
- test/fixtures/todomvc-ng2/src/app/shared/interfaces/clock.interface.ts
- test/fixtures/todomvc-ng2/src/app/shared/interfaces/interfaces.ts
- test/fixtures/todomvc-ng2/src/app/shared/pipes/first-upper.pipe.ts
- test/fixtures/todomvc-ng2/src/app/shared/services/todo.store.ts
- test/src/cli/cli-export.spec.ts
partly closes #937
Parses the @deprecated jsdoc tag so it can at least be used with the JSON output file, which is required by our team.
Can now more easily be further implemented so it is also displayed.
> feat: read jsdoc deprecated

- src/templates/partials/menu.hbs
I noticed that compodoc does not display the configured `customLogo` when the OS/browser is in dark mode. This PR fixes this issue.
I could not find any reason why the custom logo received the `data-type="compodoc-logo"` so I changed it to `custom-logo` and changed the `data-src` to `src`. The `data-type` as well as `data-src` seemed to only be used to determine whether to show the inverted logo. This is not necessary for the custom logo since we can assume users want their logo to be shown everywhere.
In the future we might want to add a `customDarkLogo` option to allow users to specify their own inverted logo.
- generate a compodoc documentation using a custom logo and switch your Operating system to "dark mode"
- reload the documentation to see that the custom logo is still shown
> fix: show custom logo even when in dark mode

- src/locales/pt-BR.ts
Fixes missing letter in unit test coverage translation for pt-BR.
> refactor(pt-BR.ts): fix misspeling in pt-BR translation

- src/utils/router-parser.util.ts
#1108, #403, #885
Compodoc has had this long-standing issue for quite some time now, and it's baring the entry for a lot of companies to utilize this library. The majority of mid-sized+ companies will utilize aliases for imports. Previously, the current work-around was to simply use relative imports for the routes:
`../core/components/somecomponent/somecomponent.route.ts`
instead of a nice import path of:
`app/core/components/somecomponent/somecomponent.route.ts`
This doesn't look like that big of a deal, but when you're importing sibling & nested routes, it becomes quite the hassle at scale.
In my case, I was originally receiving a path with the value of: 
`C:/Users/Benge/Documents/GitHub/@myclient/src/app/app/core/components/patients-list/patients-list.routes.ts`
With the issue being …
> Fix: Routing aliases 

- src/app/compiler/angular/deps/helpers/class-helper.ts
Assign the variable value to itself when its value is `true` - use a logical operator OR (||)
> fix(app): Fix reading class decorators

- src/app/compiler/angular-dependencies.ts
- src/utils/kind-to-type.ts
- test/src/cli/cli-export.spec.ts
Fix matching the default value and radio options for any @Input() of enum type
> fix(app): Fix enum member types parsing

- src/app/compiler/angular/deps/helpers/class-helper.ts
Currently only the `kind` of a set accessor is parsed. I  see no reason not to also parse the full type in the same way it is parsed normally.
> feat: fully parse set accessor type
